title: My Portfolio
description: Website to showcase my projects
show_downloads: false
show_resume: true
resume_url: https://drive.google.com/file/d/1pHoCx7hFStZErq-d8E4ukYHmfi7QpkT7/view?usp=sharing
google_analytics:
github:
  is_project_page: true
  home_url: https://gs1293.github.io/
theme: jekyll-theme-cayman
